Update README.md, build.gradle and workflows

diff --git a/.github/workflows/gradle-publish-snapshot.yml b/.github/workflows/gradle-publish-snapshot.yml
--- a/.github/workflows/gradle-publish-snapshot.yml
+++ b/.github/workflows/gradle-publish-snapshot.yml
@@ -2,26 +2,55 @@ name: Gradle Publish [snapshot]
 
 on:
   workflow_dispatch:
+  schedule:
+    - cron: "0 15 * * 5"  # friday 15:00 UTC
 
 jobs:
   check-branch:
     runs-on: ubuntu-latest
     steps:
       - name: Check Branch
-        if: github.ref != 'refs/heads/main'
+        if: startsWith(github.ref, 'refs/heads/')
         run: |
-          echo "::error title=wrong branch selected::this workflow must be run on the 'main' branch"
-          exit 1
+          BRANCH="${GITHUB_REF#refs/heads/}"
+          if [[ "$BRANCH" != "main" && "$BRANCH" != release/* ]]; then
+            echo "::error title=wrong branch selected::this workflow must be run on 'main' or 'release/*' branches"
+            exit 1
+          fi
 
-  publish-snapshot:
-    needs: check-branch
-
+  check-updates:
     runs-on: ubuntu-latest
+    outputs:
+      should_run: ${{ steps.check.outputs.should_run }}
     steps:
       - name: Checkout
         uses: actions/checkout@v5
         with:
-          ref: main
+          fetch-depth: 50
+
+      - name: Check if SNAPSHOT publish is applicable
+        id: check
+        run: |
+          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            echo "::notice::publish will always execute on manual trigger"
+            echo "should_run=true" >> $GITHUB_OUTPUT
+          else
+            if git log --since="7 days ago" --oneline | grep .; then
+              echo "::notice::commits found within last 7 days window, publish will execute"
+              echo "should_run=true" >> $GITHUB_OUTPUT
+            else
+              echo "::notice::no commits found within last 7 days window, publish will abort"
+              echo "should_run=false" >> $GITHUB_OUTPUT
+            fi
+          fi
+
+  publish-snapshot:
+    needs: [ check-branch, check-updates ]
+    if: needs.check-updates.outputs.should_run == 'true'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v5
 
       - name: Set up JDK 17
         uses: actions/setup-java@v5
